/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <signal.h>

#include "time.h"
#include "time_cnt.h"
int *
get_time_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = timer_get_tod();
	return &(result);
}

int *
delay_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	timer_delay(*argp);
	return &result;
}
